import styled from "@emotion/styled";
import {
	space,
	borders,
	borderRadius,
	borderColor,
	color,
	flex,
	width,
	minWidth,
	maxWidth,
	height,
	minHeight,
	maxHeight,
	order,
	alignSelf,
	fontSize,
	fontStyle,
	fontWeight,
	textAlign,
	position,
	top,
	right,
	bottom,
	left,
	zIndex,
	overflow,
	display,
	lineHeight,
	
	AlignSelfProps,
	BackgroundColorProps,
	BackgroundImageProps,
	BackgroundPositionProps,
	BackgroundProps,
	BackgroundRepeatProps,
	BackgroundSizeProps,
	BorderColorProps,
	BorderProps,
	BordersProps,
	BottomProps,
	BoxShadowProps,
	ColorProps,
	ColorStyleProps,
	DisplayProps,
	FlexProps,
	FontSizeProps,
	HeightProps,
	JustifySelfProps,
	LeftProps,
	MaxHeightProps,
	MaxWidthProps,
	MinHeightProps,
	MinWidthProps,
	PositionProps,
	RightProps,
	SizeProps,
	SpaceProps,
	TextStyleProps,
	TopProps,
	WidthProps,
	ZIndexProps,
	VerticalAlignProps
} from "styled-system";

export interface BoxProps
    extends AlignSelfProps,
        BackgroundColorProps,
        BackgroundImageProps,
        BackgroundPositionProps,
        BackgroundProps,
        BackgroundRepeatProps,
        BackgroundSizeProps,
        BorderColorProps,
        BorderProps,
        BordersProps,
        BottomProps,
        BoxShadowProps,
        ColorProps,
        ColorStyleProps,
        DisplayProps,
        FlexProps,
        FontSizeProps,
        HeightProps,
        JustifySelfProps,
        LeftProps,
        MaxHeightProps,
        MaxWidthProps,
        MinHeightProps,
        MinWidthProps,
        PositionProps,
        RightProps,
        SizeProps,
        SpaceProps,
        TextStyleProps,
        TopProps,
        WidthProps,
        ZIndexProps,
        VerticalAlignProps {
            boxStyle?: string;
        };

const Box: React.FunctionComponent<BoxProps> = styled("div")<any>(
	space,
	borders,
	borderRadius,
	borderColor,
	color,
	flex,
	width,
	minWidth,
	maxWidth,
	height,
	minHeight,
	maxHeight,
	order,
	alignSelf,
	fontSize,
	fontStyle,
	fontWeight,
	textAlign,
	position,
	top,
	right,
	bottom,
	left,
	zIndex,
	overflow,
	display,
	lineHeight,
);

export default Box;
